server:
  port: 8090
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      mvc:
        routes:
          - id: students-service
            uri: ${STUDENTS_URL:http://localhost:8080/students}
            predicates:
              - Path=/api/students/**
            filters:
              - StripPrefix=1
          - id: courses-service
            uri: ${COURSES_URL:http://localhost:8081/courses}
            predicates:
              - Path=/api/courses/**
            filters:
              - StripPrefix=1