server:
  port: 8090
#spring:
#  application:
#    name: gateway-server
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: students-service
#            uri: ${STUDENTS_URL:http://localhost:8080/students}
#            predicates:
#              - Path=/api/students/**
#            filters:
#              - StripPrefix=1
#          - id: courses-service
#            uri: ${COURSES_URL:http://localhost:8081/courses}
#            predicates:
#              - Path=/api/courses/**
#            filters:
#              - StripPrefix=1
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${AUTH_SERVER:http://localhost:9000}
#          jwk-set-uri: ${AUTH_SERVER:http://localhost:9000}/oauth2/jwks
#      client:
#        registration:
#          gateway-service:
#            provider: spring
#            client-id: gateway-service
#            client-secret: 12345
#            authorization-grant-type: authorization_code
#            redirect-uri: ${REDIRECT_URL:http://localhost:8090/authorized}
#            scope:
#              - openid
#              - profile
#              - read
#              - write
#            client-name: gateway-service
#        provider:
#          spring:
#            issuer-uri: ${AUTH_SERVER:http://localhost:9000}